version: '3'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysqldb